// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class Eps_Info
{
    public string Stock_Id { get; set; }

    public decimal? Eps_Acc_4Q { get; set; }

    public string Eps_Acc_4Q_Interval_Start { get; set; }

    public string Eps_Acc_4Q_Interval_End { get; set; }
}