// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class History
{
    public int History_Id { get; set; }

    public string Content { get; set; }

    public DateTime? Modify_Date_Time { get; set; }

    public string Modify_User { get; set; }

    public DateTime Create_Date_Time { get; set; }

    public string Create_User { get; set; }
}