// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class Revenue_Info
{
    public string Stock_Id { get; set; }

    public string Interval_Year { get; set; }

    public string Interval_Month { get; set; }

    public decimal? MoM { get; set; }

    public decimal? YoYMonth { get; set; }

    public decimal? YoY { get; set; }
}