// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SBH.Repositories.Models;

public partial class SBHContext : DbContext
{
    public SBHContext(DbContextOptions<SBHContext> options)
        : base(options)
    {
    }

    public virtual DbSet<User_Role> User_Role { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User_Role>(entity =>
        {
            entity.HasKey(e => e.Role_Id).HasName("PK__User_Rol__D80AB4BB6926C616");

            entity.Property(e => e.Role_Id).ValueGeneratedNever();
            entity.Property(e => e.Role_Name).HasMaxLength(16);
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.User_Id).HasName("PK_Users_1");

            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(64);
            entity.Property(e => e.Email).HasMaxLength(128);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(512);
            entity.Property(e => e.Password_Salt)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.User_Name)
                .IsRequired()
                .HasMaxLength(32);

            entity.HasOne(d => d.RoleNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.Role)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__Role__4CA06362");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}