// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class Stock_Info
{
    public string Stock_Id { get; set; }

    public string Stock_Name { get; set; }

    public string Market { get; set; }

    public string Industry_Type { get; set; }

    public string CFICode { get; set; }
}