// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class User_Role
{
    public int Role_Id { get; set; }

    public string Role_Name { get; set; }

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}