// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class Users
{
    public int User_Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Password_Salt { get; set; }

    public string User_Name { get; set; }

    public string Email { get; set; }

    public int Role { get; set; }

    public virtual User_Role RoleNavigation { get; set; }
}