// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SBH.Repositories.Models;

public partial class Volume_Detail
{
    public string Stock_Id { get; set; }

    public DateTime Tx_Date { get; set; }

    public int Foreign_Diff_VolK { get; set; }

    public int Dealer_Diff_VolK { get; set; }

    public int InvestmentTrust_Diff_VolK { get; set; }

    public int VolumeK { get; set; }
}